
from fastapi import APIRouter
import random

router = APIRouter(prefix="/trivia", tags=["Trivia"])

TRIVIA_FACTS = [
    "Psycho (1960) filminde kan efekti için çikolata şurubu kullanılmıştır.",
    "The Godfather filminde Marlon Brando, çenesini daha önde göstermek için ağzına pamuk tıkamıştır.",
    "Hababam Sınıfı filmindeki 'Güdük Necmi' karakterini oynayan Halit Akçatepe, gerçek hayatta öğretmendi.",
    "Tosun Paşa filmindeki 'Yeşil Vadi' sahneleri, aslında İstanbul Kemerburgaz'da çekilmiştir.",
    "Titanic filmindeki çizim sahnesinde görülen eller, Leonardo DiCaprio'ya değil, yönetmen James Cameron'a aittir.",
    "Iron Man (2008) filminin çekimleri başladığında senaryo henüz tamamlanmamıştı; diyalogların çoğu doğaçlamadır.",
    "Yüzüklerin Efendisi filminde Gandalf, Hobbit evinde kafasını avizeye çarptığı sahnede aslında gerçekten çarpmıştır ama rolü bozmamıştır.",
    "Matrix filmindeki o meşhur 'yeşil kodlar' aslında Japonca suşi tariflerinden oluşmaktadır.",
    "Fight Club'da Brad Pitt ve Edward Norton gerçekten sarhoş olup golf topu fırlatmışlardır.",
    "Leon: The Professional filminde Natalie Portman'ın ailesinin sigara içmesine izin vermediği için karakteri filmde sigarayı hiç yakmaz.",
    "Cem Yılmaz'ın G.O.R.A. filmi, Türk sinema tarihinin o döneme kadarki en pahalı prodüksiyonuydu.",
    "Eşkıya (1996), Türk sinemasının yeniden doğuşu olarak kabul edilir ve gişe rekorları kırmıştır.",
    "Kemal Sunal, 'Süt Kardeşler' filmindeki Gulyabani'den gerçek hayatta da korktuğunu söylemiştir.",
    "Şener Şen, hem Hababam Sınıfı'nda Badi Ekrem'i hem de Eşkıya'da Baran'ı oynayarak komedi ve dramadaki ustalığını kanıtlamıştır.",
    "Joker (2019) filmi için Joaquin Phoenix 23 kilo vermiştir.",
    "Terminator filminde Arnold Schwarzenegger sadece 700 kelime konuşmuştur.",
    "Star Wars'taki Darth Vader'ın o meşhur nefes sesi, bir dalış tüpü regülatörü kullanılarak kaydedilmiştir.",
    "Rocky filmindeki bütçe o kadar düşüktü ki, Sylvester Stallone köpeğini satmak zorunda kalmıştı (sonra geri aldı).",
    "Pulp Fiction'daki çantanın içinde ne olduğu asla açıklanmamıştır, ama içinde turuncu bir ampul vardır.",
    "Zeki Demirkubuz ve Nuri Bilge Ceylan arasındaki 'küslük' Türk sinemasının en bilinen dedikodularından biridir.",
    "Vizontele filmindeki 'Baba akü yok!' repliği tamamen doğaçlamadır.",
    "Harry Potter serisindeki Hogwarts tabloları için film ekibinin yüzleri kullanılmıştır.",
    "Inception filminin süresi 2 saat 28 dakikadır. Bu, 'Non, je ne regrette rien' şarkısının süresi olan 2 dakika 28 saniyeye bir göndermedir.",
    "Münir Özkul ve Adile Naşit, Neşeli Günler gibi birçok filmde karı-koca rolü oynamışlardır ama gerçekte hiç evlenmemişlerdir.",
    "Ölümlü Dünya filmindeki 'Mermer Ailesi' aslında bir suç örgütüdür.",
    "Haluk Bilginer: Persona (Şahsiyet) dizisindeki Agâh Beyoğlu rolüyle Uluslararası Emmy Ödülü'nü kazanan ilk Türk oyuncu olmuştur.",
    "Cem Yılmaz: Pek Yakında filmindeki set ortamını o kadar gerçekçi kurmuştur ki, filmde kullanılan tüm sinema ekipmanları aslında koleksiyonluk gerçek antikalar ve profesyonel cihazlardı.",
    "Feyyaz Yiğit: Gibi dizisindeki o meşhur uzun ve absürt diyalogların birçoğu aslında sette doğaçlama gelişmiş, sonradan senaryoya eklenmiştir.",
    "Tuba Büyüküstün: Birleşmiş Milletler (UNICEF) İyi Niyet Elçisi seçilen ilk Türk oyuncudur ve dünya çapında mülteci çocuklarla ilgili projelere liderlik etmektedir.",
    "Taner Ölmez: Mucize Doktor rolüne hazırlanırken otizm spektrumundaki bireylerle aylar geçirmekle kalmamış, tıbbi terimleri ezberlemek için gerçek bir tıp öğrencisi gibi çalışmıştır.",
    "Ezgi Mola: Masumlar Apartmanı dizisindeki Safiye rolü için her gün saatlerce süren makyaj ve hazırlık sürecinin yanı sıra, karakterin psikolojisini anlamak için uzmanlardan destek almıştır.",
    "Ahmet Mümtaz Taylan: Sadece bir oyuncu değil, aynı zamanda çok başarılı bir yönetmendir; hatta birçok popüler dizinin bazı bölümlerini o yönetmiştir.",
    "Hazar Ergüçlü: BBC yapımı The Mallorca Files dizisinde yer alarak uluslararası dijital platformlarda Türkiye'yi temsil eden oyunculardan biri olmuştur.",
    "Beren Saat: Atiye (The Gift) dizisindeki bazı mağara sahnelerinin çekimleri sırasında gerçek mekanların atmosferini bozmamak için çok dar ve zorlu koşullarda çalışmıştır.",
    "Metin Akdülger: Muhteşem Yüzyıl Kösem dizisindeki IV. Murad rolü için hem fiziksel olarak kas kütlesini artırmış hem de binicilik ve kılıç kullanma eğitimleri almıştır.",
    "Ölümlü Dünya: Filmin meşhur çatışma sahneleri, Hollywood standartlarında bir aksiyon koreografisi ekibiyle haftalarca prova edilerek çekilmiştir.",
    "Nuri Bilge Ceylan: Ahlat Ağacı filminin senaryosu o kadar uzundu ki, ilk kurgu bittiğinde film 5 saatten fazlaydı; yönetmen bunu sinema formatına indirmek için çok zorlandığını söylemiştir.",
    "Müslüm: Filmde Müslüm Gürses'in gençliğini canlandıran Şahin Kendirci, yarışma programından keşfedilip bu rol için seçilmiştir.",
    "Bergüzar Korel: Vatanım Sensin dizisindeki rolü için o dönemin konuşma dilini ve protokollerini öğrenmek adına tarihçilerle çalışmıştır.",
    "Ayla: Filmde kullanılan kostümlerin bir kısmı, 1950'li yılların Kore Savaşı dönemindeki orijinal kıyafetlerden esinlenerek Güney Kore ve Türkiye'de özel olarak dikilmiştir.",
    "Bir Başkadır: Berkun Oya, dizideki meşhur 'Meryem' karakterinin o eşsiz şivesini ve tavrını oluşturmak için oyuncu Öykü Karayel ile aylarca karakter çalışması yapmıştır.",
    "Cingöz Recai: Kenan İmirzalıoğlu'nun başrolünde olduğu filmde, Peyami Safa'nın romanındaki havayı yakalamak için St. Petersburg'da çok zorlu hava şartlarında çekim yapılmıştır.",
    "7. Koğuştaki Mucize: Bu film, Güney Kore yapımı orijinalinden (Miracle in Cell No. 7) daha fazla izlenerek dünya çapında (özellikle Latin Amerika'da) büyük bir başarı yakalamıştır.",
    "Kelebeğin Rüyası: Yılmaz Erdoğan, bu film için Zonguldak'taki maden ocaklarını ve 1940'ların atmosferini yeniden yaratmak adına Türkiye'nin o döneme kadarki en büyük bütçelerinden birini kullanmıştır.",
    "Ahlat Ağacı: Filmin başrol oyuncusu Doğu Demirkol aslında bir stand-up komedyenidir; Nuri Bilge Ceylan onu YouTube'daki videolarını izleyerek keşfetmiştir.",
    "Cem Yılmaz: G.O.R.A. filmindeki Erşan Kuneri karakteri o kadar sevildi ki, yıllar sonra bu karakterin hayatını anlatan özel bir dizi çekildi.",
    "Halit Ergenç: Muhteşem Yüzyıl dizisindeki Kanuni Sultan Süleyman rolü için tam 1,5 yıl boyunca sakallarını hiç kesmemiştir.",
    "Kıvanç Tatlıtuğ: Kelebeğin Rüyası filmindeki verem hastası şair Muzaffer Tayyip Uslu rolü için yaklaşık 20 kilo vererek tanınmaz hale gelmiştir.",
    "Engin Günaydın: Avrupa Yakası'ndaki Burhan Altıntop karakterinin o meşhur yürüyüşünü ve tavırlarını, Tokat'ta çocukken gözlemlediği gerçek insanlardan esinlenerek oluşturmuştur.",
    "Merve Dizdar: Kuru Otlar Üstüne filmindeki performansıyla, Cannes Film Festivali'nde 'En İyi Kadın Oyuncu' ödülünü kazanan ilk Türk kadın oyuncu olmuştur.",
    "Aras Bulut İynemli: 7. Koğuştaki Mucize filmindeki Memo rolü için zihinsel engelli bireylerle uzun süre vakit geçirmiş ve çekimler boyunca karakterden hiç çıkmamıştır.",
    "Ezgi Mola: Sinema kariyerine ek olarak, YouTube ve sosyal medyada yarattığı tiplemelerle modern dönemin dijital karakter inşasında öncü olmuştur.",
    "Ahmet Kural & Murat Cemcir: Bu ikili, Çalgı Çengi filminin çekimleri sırasında bütçe yetersizliğinden dolayı birçok sahnede kendi kıyafetlerini kullanmışlardır.",
    "Serkan Keskin: Leyla ile Mecnun'un İsmail Abi'si olarak devleşen oyuncu, aslında çok disiplinli bir tiyatro kökenine sahiptir ve Semaver Kumpanya'nın kurucularındandır.",
    "Kemal Sunal: Aslında 10 Kasım doğumludur; ancak Atatürk'ün ölüm yıldönümüne denk geldiği için doğum gününü her yıl 11 Kasım'da kutlamıştır.",
    "Hulusi Kentmen: Filmlerin tonton babası ve fabrikatörü, gerçek hayatta denizci bir astsubaydı ve klasik müzik çalan bir keman sanatçısıydı.",
    "Şener Şen: Sinemaya atılmadan önce işportacılık, dolmuş şoförlüğü ve Muş'ta köy öğretmenliği yapmıştır.",
    "Türkan Şoray: İlk rolü için yapımcı 'Yeteri kadar param yok, yeni bir kız bulun' deyince tesadüfen seçilmiştir.",
    "Cüneyt Arkın: Asıl mesleği tıp doktorluğudur; aksiyon sahnelerindeki başarısını anatomik bilgisine ve sirklerde aldığı eğitimlere borçludur.",
    "Kemal Sunal: Liseyi (Vefa Lisesi) 'okumayı çok sevdiği için' tam 11 yılda bitirmiştir.",
    "Sadri Alışık: Sinemada dublajsız oynamanın öncülerinden biridir.",
    "Filiz Akın: Yeşilçam'da 'sarışın kadından esas kız olmaz' algısını yıkan ilk oyuncudur.",
    "Tarık Akan: Hababam Sınıfı afişlerinde bir ilki gerçekleştirerek, kendi isminin Münir Özkul'dan sonra yazılmasını istemiştir.",
    "Adile Naşit: Kahkahasıyla tanınsa da, aslında çok hüzünlü bir hayatı olmuş; 16 yaşındaki oğlunu bir ameliyat sırasında kaybetmiştir.",
    "Christopher Nolan: CGI (bilgisayar efektleri) kullanmaktan nefret eder. Tenet filminde gerçek bir Boeing 747 uçağını bir binaya çarptırıp patlatmış, Interstellar için ise devasa mısır tarlalarını gerçekten ektirmiştir.",
    "Alfred Hitchcock: Kendi filmlerinde kısa süreliğine görünmesiyle (cameo) ünlüdür. Seyirciler film boyunca onu aramaktan konuya odaklanamadığı için, Hitchcock sahnelerini filmin en başına koymaya başlamıştır.",
    "James Cameron: Titanic çekimleri sırasında ekibin yemeklerine biri tarafından yanlışlıkla halüsinojen bir madde karıştırılmış ve aralarında Bill Paxton'ın da olduğu 50'den fazla kişi hastanelik olmuştur.",
    "Keanu Reeves: John Wick serisindeki aksiyon sahnelerinin %90'ından fazlasını dublör kullanmadan kendisi gerçekleştirmiştir ve bu rol için aylarca taktiksel silah eğitimi almıştır.",
    "Heath Ledger: The Dark Knight filmindeki Joker karakterine hazırlanmak için bir otel odasına kapanıp haftalarca dış dünyayla bağını kesmiş ve karakterin o meşhur ürkütücü günlüğünü oluşturmuştur.",
    "Harrison Ford: Sadece bir oyuncu değil, aynı zamanda lisanslı bir pilottur ve kendi uçaklarını uçurabilmektedir.",
    "Rowan Atkinson (Mr. Bean): Sanılanın aksine çok ciddi bir akademik geçmişe sahiptir ve Elektrik Mühendisliği alanında Master derecesi vardır.",
    "James Earl Jones: Hem Star Wars'un ikonik kötüsü Darth Vader'ı hem de Aslan Kral'daki Mufasa'yı seslendiren kişidir.",
    "Kit Harington: Gerçek hayatta da soylu bir aileden gelmektedir; kendisi 15. Baronet Sir David Robert Harington'ın oğludur ve İngiltere Kralı II. Charles'ın soyuna dayanmaktadır.",
    "Angelina Jolie: Birleşmiş Milletler mülteci elçisi olarak dünya genelinde 60'tan fazla insani yardım görevine katılmıştır.",
    "Jackie Chan: Sinema dünyasında sadece oyuncu olarak değil, aynı zamanda yapımcı ve yönetmen olarak da aktif bir kariyere sahiptir.",
    "Matt Damon ve Tom Holland: 2026 yılında vizyona girmesi beklenen, Christopher Nolan'ın yönettiği 'The Odyssey' filminde baba ve oğulu (Odysseus ve Telemakhos) canlandıracaklardır.",
    "Julie Andrews: The Princess Diaries 2 filmi, usta oyuncuyu uzun bir aradan sonra yeniden şarkı söylemeye ikna eden projedir.",
    "Tom Holland: Meşhur 'Lip Sync Battle' yarışmasında Rihanna'nın Umbrella şarkısıyla yaptığı performans hala unutulmazlar arasındadır.",
    "Bradley Whitford ve Noah Wyle: Her iki oyuncu da 2026'da Hollywood Şöhretler Kaldırımı'na isimlerini yazdıracak ünlüler arasındadır.",
    "Ke Huy Quan: Oscar kazanmadan önce oyunculuğa uzun bir ara vermiş ve sektörün mutfağında çalışmıştır.",
    "Rami Malek: Emmy ve Oscar ödüllü oyuncu, 2026 yılında Hollywood Şöhretler Kaldırımı'nda yıldız sahibi olacak seçkin sınıfa dahil edilmiştir.",
    "Miley Cyrus: Genç yaşta büyük başarılara imza atan şarkıcı ve oyuncu, 2026 yılı sınıfıyla birlikte kendi yıldızına kavuşacaktır.",
    "Steve McQueen: Oyunculuğunun yanı sıra otomobil tutkusuyla bilinir ve çok nadir bir otomobil koleksiyonuna sahiptir.",
]

@router.get("/random")
def get_random_fact():
    fact = random.choice(TRIVIA_FACTS)
    return {"fact": fact}
